"""
Local RiskAgent: gates a merged signal against the fund's risk mandate.

Deliberately zero LLM involvement (architecture doc, section 2) -- every
rule below is a plain function so each one can independently produce a
risk_notes entry and be unit-tested in isolation.

The RiskAgent is the per-ticker risk layer. PortfolioRiskCoordinator
(portfolio/coordinator.py) is the portfolio-wide layer that looks across
all tickers at once.

Position sizing and per-ticker/per-sector caps are two independent
concepts:

1. compute_position_size() calculates the raw risk-based position size.
2. compute_capped_size() limits that size to the remaining portfolio
   capacity under the per-ticker and per-sector caps.
3. The cap checks then validate the resulting proposed exposure.

This prevents ordinary risk-based sizing from being rejected simply because
the raw position size is larger than the remaining cap room.

Important invariant:
    ticker_room_value >= 0
    sector_room_value >= 0

Available room is exposed as a non-negative value for observability. If
existing holdings already exceed a configured cap, available room is reported
as $0 rather than a misleading negative amount. The actual cap checks remain
responsible for detecting any existing cap breach.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from config.risk_config import RiskConfig
from agents.signal_merger import MergedSignal
from portfolio.circuit_breaker import CircuitBreaker
from portfolio.correlation import check_correlation as _check_correlation
from portfolio.state import PortfolioSnapshot


# =============================================================================
# DATA STRUCTURES
# =============================================================================


@dataclass
class RiskCheckResult:
    """Result of one deterministic risk rule."""

    rule: str
    passed: bool
    note: str


@dataclass
class RiskDecision:
    """Final deterministic risk decision for one ticker."""

    approved: bool
    ticker: str
    proposed_shares: float
    raw_shares: float = 0.0
    checks: list[RiskCheckResult] = field(default_factory=list)

    @property
    def risk_notes(self) -> list[str]:
        """Human-readable notes generated by every risk check."""
        return [c.note for c in self.checks]


# =============================================================================
# INDIVIDUAL RISK RULES
# =============================================================================


def check_circuit_breaker(
    portfolio: PortfolioSnapshot,
    config: RiskConfig,
) -> RiskCheckResult:
    """
    Check whether the portfolio has breached the daily drawdown circuit
    breaker.
    """

    breaker = CircuitBreaker(threshold_pct=config.circuit_breaker.daily_drawdown_pct)

    tripped = breaker.check(
        portfolio.starting_equity,
        portfolio.equity,
    )

    pnl_pct = CircuitBreaker.daily_pnl_pct(
        portfolio.starting_equity,
        portfolio.equity,
    )

    return RiskCheckResult(
        rule="circuit_breaker",
        passed=not tripped,
        note=(
            f"Circuit breaker: today's P&L {pnl_pct:.2%} "
            f"{'<=' if tripped else '>'} "
            f"threshold {config.circuit_breaker.daily_drawdown_pct:.2%} -> "
            f"{'HALTED' if tripped else 'ok'}."
        ),
    )


def check_concurrent_positions(
    portfolio: PortfolioSnapshot,
    ticker: str,
    config: RiskConfig,
) -> RiskCheckResult:
    """
    Prevent opening a new ticker when the maximum number of concurrent
    positions has already been reached.

    Existing positions are allowed to continue being managed.
    """

    open_count = len(portfolio.positions)
    already_held = ticker in portfolio.positions

    would_exceed = not already_held and open_count + 1 > config.max_concurrent_positions

    return RiskCheckResult(
        rule="concurrent_positions",
        passed=not would_exceed,
        note=(
            f"Concurrent positions: {open_count} open, "
            f"max {config.max_concurrent_positions} -> "
            f"{'would exceed limit' if would_exceed else 'ok'}."
        ),
    )


def compute_position_size(
    equity: float,
    entry_price: float,
    atr: float,
    config: RiskConfig,
) -> float:
    """
    Calculate the raw risk-based position size.

    Formula:

        risk_dollars = equity * equity_risk_pct
        stop_distance = ATR * atr_stop_multiple
        shares = risk_dollars / stop_distance

    This function intentionally does NOT apply portfolio exposure caps.
    Those are applied by compute_capped_size().
    """

    if atr <= 0 or entry_price <= 0:
        return 0.0

    risk_dollars = equity * config.position_sizing.equity_risk_pct

    stop_distance = atr * config.position_sizing.atr_stop_multiple

    if stop_distance <= 0:
        return 0.0

    return round(
        risk_dollars / stop_distance,
        4,
    )


def compute_capped_size(
    risk_based_shares: float,
    entry_price: float,
    portfolio: PortfolioSnapshot,
    ticker: str,
    sector: str,
    config: RiskConfig,
) -> tuple[float, float, float]:
    """
    Clamp the raw risk-based share count to the remaining room under both
    per-ticker and per-sector exposure caps.

    Returns:

        (
            capped_shares,
            ticker_room_value,
            sector_room_value,
        )

    Important invariant:

        ticker_room_value >= 0
        sector_room_value >= 0

    If existing holdings already exceed a configured cap, available room is
    reported as $0 rather than a negative number.

    The separate cap-check functions still detect the resulting exposure
    breach, so this does not hide an already-invalid portfolio state.
    """

    if entry_price <= 0:
        return 0.0, 0.0, 0.0

    # -------------------------------------------------------------------------
    # Existing exposure for this ticker
    # -------------------------------------------------------------------------

    existing = portfolio.positions.get(ticker)

    existing_value = existing.market_value if existing else 0.0

    # -------------------------------------------------------------------------
    # Remaining per-ticker capacity
    # -------------------------------------------------------------------------

    raw_ticker_room_value = (
        config.per_ticker_cap_pct * portfolio.equity - existing_value
    )

    # Available room is never exposed as negative.
    ticker_room_value = max(
        0.0,
        raw_ticker_room_value,
    )

    # -------------------------------------------------------------------------
    # Existing sector exposure
    #
    # Do not double-count the current ticker here because existing_value is
    # added separately below.
    # -------------------------------------------------------------------------

    sector_value = sum(
        p.market_value
        for t, p in portfolio.positions.items()
        if p.sector == sector and t != ticker
    )

    raw_sector_room_value = config.per_sector_cap_pct * portfolio.equity - (
        sector_value + existing_value
    )

    # Available room is never exposed as negative.
    sector_room_value = max(
        0.0,
        raw_sector_room_value,
    )

    # -------------------------------------------------------------------------
    # The actual executable room is the tighter of the two caps.
    # -------------------------------------------------------------------------

    room_value = min(
        ticker_room_value,
        sector_room_value,
    )

    room_shares = room_value / entry_price if entry_price > 0 else 0.0

    capped_shares = round(
        max(
            0.0,
            min(
                risk_based_shares,
                room_shares,
            ),
        ),
        4,
    )

    return (
        capped_shares,
        ticker_room_value,
        sector_room_value,
    )


def check_per_ticker_cap(
    portfolio: PortfolioSnapshot,
    ticker: str,
    proposed_shares: float,
    entry_price: float,
    config: RiskConfig,
) -> RiskCheckResult:
    """
    Validate resulting exposure against the per-ticker cap.

    proposed_shares is expected to already have been capped by
    compute_capped_size().
    """

    existing = portfolio.positions.get(ticker)

    existing_value = existing.market_value if existing else 0.0

    proposed_value = existing_value + proposed_shares * entry_price

    pct = proposed_value / portfolio.equity if portfolio.equity else 1.0

    passed = pct <= config.per_ticker_cap_pct + 1e-9

    return RiskCheckResult(
        rule="per_ticker_cap",
        passed=passed,
        note=(
            f"Per-ticker cap ({ticker}): would be {pct:.1%} of equity, "
            f"cap {config.per_ticker_cap_pct:.0%} -> "
            f"{'ok' if passed else 'BREACH (no room left)'}."
        ),
    )


def check_per_sector_cap(
    portfolio: PortfolioSnapshot,
    ticker: str,
    sector: str,
    proposed_shares: float,
    entry_price: float,
    config: RiskConfig,
) -> RiskCheckResult:
    """
    Validate resulting sector exposure against the per-sector cap.

    proposed_shares is expected to already have been capped by
    compute_capped_size().
    """

    sector_value = sum(
        p.market_value
        for t, p in portfolio.positions.items()
        if p.sector == sector and t != ticker
    )

    existing = portfolio.positions.get(ticker)

    existing_value = existing.market_value if existing else 0.0

    proposed_sector_value = (
        sector_value + existing_value + proposed_shares * entry_price
    )

    pct = proposed_sector_value / portfolio.equity if portfolio.equity else 1.0

    passed = pct <= config.per_sector_cap_pct + 1e-9

    return RiskCheckResult(
        rule="per_sector_cap",
        passed=passed,
        note=(
            f"Per-sector cap ({sector}): would be {pct:.1%} of equity, "
            f"cap {config.per_sector_cap_pct:.0%} -> "
            f"{'ok' if passed else 'BREACH (no room left)'}."
        ),
    )


def check_correlation(
    portfolio: PortfolioSnapshot,
    ticker: str,
    config: RiskConfig,
) -> RiskCheckResult:
    """Check correlation against existing portfolio holdings."""

    held_tickers = list(portfolio.positions.keys())

    result = _check_correlation(
        ticker,
        held_tickers,
        portfolio.correlation_matrix,
        config.correlation.max_correlation,
    )

    passed = not result["flagged"]

    return RiskCheckResult(
        rule="correlation",
        passed=passed,
        note=(
            (
                f"Correlation: ok, no existing holding above "
                f"{config.correlation.max_correlation}."
            )
            if passed
            else (
                f"Correlation: {ticker} at "
                f"{result['max_correlation']} vs "
                f"{result['against']} exceeds "
                f"{config.correlation.max_correlation} -> "
                f"reject/downsize."
            )
        ),
    )


# =============================================================================
# RISK AGENT ORCHESTRATION
# =============================================================================


def run_risk_agent(
    merged_signal: MergedSignal,
    ticker: str,
    sector: str,
    entry_price: float,
    atr: float,
    portfolio: PortfolioSnapshot,
    config: RiskConfig,
) -> RiskDecision:
    """
    Run every deterministic risk rule for a merged trading signal.

    Flow:

        1. Circuit breaker
        2. Signal direction
        3. Raw risk-based sizing
        4. Cap-aware sizing
        5. Concurrent-position check
        6. Per-ticker cap
        7. Per-sector cap
        8. Correlation
        9. Final approval

    The risk-based size is resized rather than rejected when it is larger than
    available exposure capacity.

    A trade is rejected because of sizing only when no executable room remains.
    """

    checks: list[RiskCheckResult] = [
        check_circuit_breaker(
            portfolio,
            config,
        )
    ]

    # -------------------------------------------------------------------------
    # Neutral signals should never reach position sizing.
    # -------------------------------------------------------------------------

    if merged_signal.direction == "neutral":
        checks.append(
            RiskCheckResult(
                rule="signal_direction",
                passed=False,
                note=("Merged signal is neutral -- no trade to evaluate."),
            )
        )

        return RiskDecision(
            approved=False,
            ticker=ticker,
            proposed_shares=0.0,
            raw_shares=0.0,
            checks=checks,
        )

    # -------------------------------------------------------------------------
    # Raw risk-based sizing
    # -------------------------------------------------------------------------

    raw_shares = compute_position_size(
        portfolio.equity,
        entry_price,
        atr,
        config,
    )

    # -------------------------------------------------------------------------
    # Apply exposure caps
    # -------------------------------------------------------------------------

    (
        capped_shares,
        ticker_room_value,
        sector_room_value,
    ) = compute_capped_size(
        raw_shares,
        entry_price,
        portfolio,
        ticker,
        sector,
        config,
    )

    # -------------------------------------------------------------------------
    # Record sizing observability
    # -------------------------------------------------------------------------

    if capped_shares < raw_shares:
        checks.append(
            RiskCheckResult(
                rule="position_sizing",
                passed=True,
                note=(
                    f"Sizing: raw risk-based size "
                    f"{raw_shares:.2f} sh "
                    f"(${raw_shares * entry_price:,.0f}) "
                    f"resized to {capped_shares:.2f} sh "
                    f"(${capped_shares * entry_price:,.0f}) "
                    f"-- ticker room ${ticker_room_value:,.0f}, "
                    f"sector room ${sector_room_value:,.0f}."
                ),
            )
        )
    else:
        checks.append(
            RiskCheckResult(
                rule="position_sizing",
                passed=True,
                note=(
                    f"Sizing: raw risk-based size "
                    f"{raw_shares:.2f} sh fits within caps, "
                    f"no resize needed."
                ),
            )
        )

    # -------------------------------------------------------------------------
    # Remaining deterministic risk checks
    # -------------------------------------------------------------------------

    checks.append(
        check_concurrent_positions(
            portfolio,
            ticker,
            config,
        )
    )

    checks.append(
        check_per_ticker_cap(
            portfolio,
            ticker,
            capped_shares,
            entry_price,
            config,
        )
    )

    checks.append(
        check_per_sector_cap(
            portfolio,
            ticker,
            sector,
            capped_shares,
            entry_price,
            config,
        )
    )

    checks.append(
        check_correlation(
            portfolio,
            ticker,
            config,
        )
    )

    # -------------------------------------------------------------------------
    # Final approval
    # -------------------------------------------------------------------------

    no_room = capped_shares <= 0.0001

    other_checks_pass = all(
        c.passed
        for c in checks
        if c.rule
        not in (
            "per_ticker_cap",
            "per_sector_cap",
        )
    )

    approved = other_checks_pass and not no_room

    # -------------------------------------------------------------------------
    # Explicit sizing rejection
    # -------------------------------------------------------------------------

    if no_room and other_checks_pass:
        checks.append(
            RiskCheckResult(
                rule="sizing_rejected",
                passed=False,
                note=(
                    f"No cap room remains for {ticker} "
                    f"in {sector} -- trade rejected, "
                    f"not resized."
                ),
            )
        )

    return RiskDecision(
        approved=approved,
        ticker=ticker,
        proposed_shares=(capped_shares if approved else 0.0),
        raw_shares=raw_shares,
        checks=checks,
    )
